name: Buildx release
on:
  release:
    types: [published]
    paths-ignore:
      - .github/workflows/buildx-latest.yml
      - .github/workflows/dockerhub-description.yml
      - .github/workflows/greetings.yml
      - .github/workflows/labels.yml
      - .github/workflows/misspell.yml
      - .github/workflows/security.yml
      - .dockerignore
      - .gitignore
      - docker-compose.yml
      - LICENSE
      - README.md
      - title.svg
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Dockerhub login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u qmcgaw --password-stdin 2>&1
      - name: Buildx Alpine image
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64,linux/386 \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            --build-arg VERSION=${GITHUB_REF##*/} \
            -t qmcgaw/cod4:${GITHUB_REF##*/} \
            --push \
            .
      - name: Buildx Debian Steam image
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64,linux/386 \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            --build-arg VERSION=steam-${GITHUB_REF##*/} \
            -f steam.Dockerfile \
            -t qmcgaw/cod4:steam-${GITHUB_REF##*/} \
            --push \
            .
      - run: curl -X POST https://hooks.microbadger.com/images/qmcgaw/cod4/8mWxKyC34UYWUF7BRtDpbB8WWt4= || exit 0
