name: Release build
on:
  release:
    types: [published]
    paths:
      - .github/workflows/release.yml
      - cmd/**
      - internal/**
      - .dockerignore
      - .golangci.yml
      - Dockerfile
      - go.mod
      - go.sum
      - server.cfg

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildx setup
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Dockerhub login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u qmcgaw --password-stdin 2>&1
      - name: Build
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64,linux/386 \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg COMMIT=`git rev-parse --short HEAD` \
            --build-arg VERSION=${GITHUB_REF##*/} \
            -t qmcgaw/cod4:${GITHUB_REF##*/} \
            --push \
            .
